version: '3.4'
services:
  auth-db:
    image: mysql:5.7.33
    container_name: popugjira-auth-mysql
    ports:
      - ${AUTH_DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${AUTH_DB_NAME}
      MYSQL_USER: ${AUTH_DB_USER}
      MYSQL_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
     - ./mysqlAuth:/var/lib/mysql
  traker-db:
    image: mysql:5.7.33
    container_name: popugjira-traker-mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
     - ./mysql:/var/lib/mysql
